import type { Doc } from "./content";

/** Doc pages (whitepaper, tokenomics, docs, audit, support, legal). */
export const docMap: Record<string, Doc> = {
  whitepaper: {
    eyebrow: "Whitepaper",
    title: "OPEN Whitepaper",
    meta: "Versión 1.2 · Actualizado en 2026",
    subtitle:
      "La especificación técnica y económica del token OPEN: su vínculo con la acción de openAI, el mecanismo de recompra y la arquitectura del protocolo.",
    hasStats: true,
    stats: [
      { value: "5,000M", label: "Suministro total" },
      { value: "30%", label: "Comisiones a recompra" },
      { value: "ERC-20", label: "Estándar del token" },
      { value: "2027", label: "OPI prevista" },
    ],
    sections: [
      { h: "Resumen ejecutivo", p: ["OPEN es un token ERC-20 cuyo valor está vinculado a las acciones de openAI y respaldado por los ingresos recurrentes del ecosistema. Una fracción de las comisiones generadas por los productos de openAI se destina, mediante un contrato auditado, a recomprar OPEN en el mercado abierto y retirarlo de circulación de forma permanente.", "El diseño persigue tres objetivos: ofrecer exposición temprana a la valoración de openAI antes de su salida a bolsa, alinear el valor del token con la adopción real de los productos, y garantizar liquidez on-chain sin custodia centralizada.", "Este documento describe el problema que aborda el protocolo, su diseño económico, su arquitectura técnica, el modelo de gobernanza y los riesgos asociados. No constituye una oferta de inversión ni asesoramiento financiero."] },
      { h: "1. Contexto y motivación", p: ["Las empresas privadas de alto crecimiento concentran gran parte de su revalorización en las fases previas a su salida a bolsa, un periodo al que el inversor minorista rara vez tiene acceso. Cuando la compañía finalmente cotiza, buena parte de la apreciación ya se ha producido y queda reservada a inversores institucionales y rondas privadas.", "OPEN propone un instrumento on-chain que tiende un puente entre esa fase privada y el inversor general: un token líquido, sin custodia y vinculado a la evolución de la compañía, que además captura valor del uso cotidiano de sus productos."] },
      { h: "2. El token OPEN", p: ["OPEN es un token fungible conforme al estándar ERC-20, desplegado sobre una red EVM con costes de transacción reducidos. El suministro total es fijo en 5.000 millones de unidades; el contrato no incluye función de acuñación adicional, por lo que la oferta solo puede mantenerse o decrecer.", "Cada OPEN representa una unidad de exposición al protocolo. No otorga derechos societarios sobre openAI ni dividendos; su valor deriva del mecanismo de anclaje a la acción y del programa de recompra descritos en este documento."] },
      { h: "3. Vínculo con la acción de openAI", p: ["El precio de referencia de OPEN se ancla a la valoración de openAI mediante un oráculo descentralizado que publica de forma periódica el valor estimado de la compañía. Antes de la salida a bolsa, ese valor procede de las rondas de financiación y de valoraciones independientes; tras la OPI, el oráculo tomará la cotización oficial de la acción como referencia.", "El anclaje no es una paridad rígida: el mercado on-chain determina el precio en cada momento, pero el oráculo proporciona la señal fundamental que guía el arbitraje y mantiene la correlación entre el token y la compañía a lo largo del tiempo."] },
      { h: "4. Acumulación de valor (value accrual)", p: ["El 30% de las comisiones netas generadas por los productos del ecosistema —openChat, la API, generación de imagen, vídeo, voz y código— se enruta de forma automática al contrato de recompra.", "El contrato adquiere OPEN en los pools de liquidez y envía los tokens a una dirección de quema verificable, de la que no pueden recuperarse. De este modo, a mayor adopción de los productos, mayor es el flujo de recompra y mayor la contracción de la oferta circulante.", "Este mecanismo convierte el uso cotidiano del ecosistema en presión de demanda estructural sobre el token, con independencia de la actividad especulativa del mercado."] },
      { h: "5. Distribución del suministro", p: ["El suministro de 5.000 millones de OPEN se distribuye así: 30% a la preventa pública, 25% a liquidez on-chain, 20% al fondo de recompra y quema, 20% a marketing y crecimiento, y 5% al equipo.", "La asignación del equipo queda bloqueada durante 36 meses con liberación lineal a partir del mes 12. La reserva de marketing se libera por tramos ligados a hitos públicos de adopción, evitando presiones de venta repentinas sobre el mercado."] },
      { h: "6. Liquidez y mercado", p: ["El 25% del suministro destinado a liquidez se despliega en pools on-chain que garantizan que cualquier inversor pueda comprar o vender OPEN en todo momento. Los compradores de preventa no están sujetos a periodos de bloqueo.", "La profundidad de los pools y los parámetros de las comisiones se calibran para minimizar el slippage en operaciones de tamaño habitual y para sostener un mercado ordenado durante los eventos de recompra."] },
      { h: "7. Arquitectura técnica", p: ["El protocolo se compone de tres contratos inteligentes independientes y auditados: el token ERC-20, el módulo de recompra y quema, y el módulo de gobernanza.", "El módulo de recompra recibe las comisiones, ejecuta las órdenes de compra contra los pools y registra cada quema con un evento verificable on-chain. El módulo de gobernanza administra los parámetros ajustables del sistema dentro de límites preestablecidos.", "Todo el código es abierto, está verificado en el explorador de bloques y puede ser auditado por cualquiera. Las direcciones de los contratos y sus ABIs se publican en la documentación para desarrolladores."] },
      { h: "8. Oráculo de precio", p: ["El oráculo agrega múltiples fuentes para publicar el valor de referencia de la compañía y el precio de mercado del token. Emplea ventanas temporales y medianas para resistir manipulaciones puntuales y picos de baja liquidez.", "En caso de discrepancia anómala entre fuentes, el oráculo entra en un modo conservador que pausa los parámetros sensibles hasta que los datos se normalizan."] },
      { h: "9. Gobernanza", p: ["Determinados parámetros del protocolo —como el porcentaje de comisiones destinado a recompra o la configuración de liquidez— pueden ajustarse mediante gobernanza on-chain, dentro de rangos máximos y mínimos codificados en los contratos.", "El objetivo a medio plazo es transferir progresivamente estas decisiones a los holders de OPEN, avanzando hacia una administración descentralizada del protocolo."] },
      { h: "10. Seguridad", p: ["Los contratos han sido revisados por auditores independientes, sin hallazgos críticos ni de severidad alta pendientes. Existe además un programa de recompensas por la divulgación responsable de vulnerabilidades.", "El protocolo es self-custody: openAI nunca tiene control sobre los fondos de los usuarios. La pérdida de las claves privadas implica la pérdida irreversible de los tokens, por lo que la custodia segura es responsabilidad del inversor."] },
      { h: "11. Hoja de ruta", p: ["2026 — Preventa pública, despliegue de liquidez on-chain y activación del mecanismo de recompra.", "2027 — Salida a bolsa de openAI e integración de la cotización oficial en el oráculo de precio.", "2028 y posteriores — Transición de la gobernanza a los holders y ampliación de los productos del ecosistema integrados en el flujo de recompra."] },
      { h: "12. Aviso legal", p: ["Este documento tiene carácter informativo y describe un concepto de diseño ficticio. openAI y el token OPEN no son reales, carecen de valor y no tienen afiliación con OpenAI. Nada de lo aquí expuesto constituye una oferta de inversión ni asesoramiento financiero."] },
    ],
  },
  tokenomics: {
    eyebrow: "Tokenomics",
    title: "Tokenomics de OPEN",
    meta: "Suministro fijo · 5.000M OPEN",
    subtitle: "Distribución del suministro, calendarios de bloqueo y el mecanismo de recompra que sostiene el valor del token.",
    hasStats: true,
    stats: [
      { value: "5,000M", label: "Suministro total" },
      { value: "30%", label: "Preventa pública" },
      { value: "20%", label: "Recompra y quema" },
      { value: "5%", label: "Equipo (lock-up 3a)" },
    ],
    sections: [
      { h: "Distribución del suministro", p: ["Preventa pública: 30%. Liquidez on-chain: 25%. Recompra y quema: 20%. Marketing: 20%. Equipo: 5% (bloqueado 3 años). El suministro total es fijo: no se acuñarán nuevos OPEN."] },
      { h: "Calendario de bloqueo", p: ["La asignación del equipo queda bloqueada durante 36 meses con liberación lineal a partir del mes 12. La reserva de marketing se libera por tramos ligados a hitos públicos de adopción."] },
      { h: "Recompra y quema", p: ["El 30% de las comisiones del ecosistema financia recompras periódicas de OPEN, que se retiran de circulación de forma permanente y verificable. Este mecanismo es el principal motor de contracción de la oferta."] },
      { h: "Liquidez", p: ["El 25% destinado a liquidez se despliega en pools on-chain para garantizar que cualquier inversor pueda comprar o vender OPEN en todo momento, sin periodos de bloqueo para los compradores de preventa."] },
    ],
  },
  docs: {
    eyebrow: "Documentación",
    title: "Documentación para desarrolladores",
    meta: "Referencia de API y contratos · v1",
    subtitle: "Guías de integración, referencia de los contratos del protocolo y endpoints para consultar precio, oferta, cartera y operaciones de OPEN.",
    sections: [
      { h: "Introducción", p: ["Esta documentación cubre todo lo necesario para integrar OPEN en una aplicación: conexión de wallet, lectura de datos de mercado, ejecución de compras e intercambios, y reacción a eventos on-chain.", "El protocolo expone dos superficies complementarias: los contratos inteligentes (para operar de forma directa y sin intermediarios) y una API de datos (para consultas de mercado y de cartera con baja latencia)."] },
      { h: "Primeros pasos", p: ["Para operar necesitas una wallet compatible: MetaMask, Coinbase Wallet, WalletConnect o Rainbow. Conecta la wallet a la red EVM del protocolo y asegúrate de disponer de saldo para las comisiones de red.", "Desde el front-end, la conexión se realiza con un proveedor estándar (EIP-1193). Una vez conectada la wallet, puedes leer saldos, solicitar firmas y enviar transacciones a los contratos del protocolo."] },
      { h: "Autenticación", p: ["Las lecturas de la API de mercado son públicas y no requieren autenticación. Las operaciones que afectan a fondos se autorizan siempre con la firma de la wallet del usuario; el protocolo nunca solicita claves privadas ni frases de recuperación.", "Para integraciones de servidor (por ejemplo, paneles internos), se emiten claves de API de solo lectura con límites de uso configurables."] },
      { h: "Contratos del protocolo", p: ["El sistema se compone de tres contratos: el token OPEN (ERC-20), el módulo de recompra y quema, y el módulo de gobernanza.", "El token implementa la interfaz ERC-20 estándar: balanceOf, transfer, approve, allowance y transferFrom, además de los eventos Transfer y Approval. Las direcciones de los tres contratos y sus ABIs están verificadas y publicadas en el explorador de bloques.", "Recomendamos fijar la versión del ABI en tu integración y validar la dirección del contrato contra la lista oficial para evitar suplantaciones."] },
      { h: "Comprar e intercambiar", p: ["Las compras con cripto y los intercambios se ejecutan contra los pools de liquidez del protocolo. El flujo típico es: approve del token de origen (si aplica), simulación de la operación para estimar el importe recibido y el slippage, y envío de la transacción de swap.", "Las compras con tarjeta se delegan en los proveedores de on-ramp Transak y MoonPay mediante sus SDK. El widget del proveedor recoge los datos de pago y, al completarse, acredita los OPEN en la wallet del usuario."] },
      { h: "API de mercado", p: ["Expone endpoints REST y WebSocket para precio en tiempo real, histórico de cotización por rango (1D, 1S, 1M, 1A, todo), oferta circulante, suministro total, volumen y capitalización.", "Los datos se sirven con marcas de tiempo y se actualizan en streaming a través de WebSocket para construir gráficos y tickers en vivo sin sondeo constante."] },
      { h: "API de cartera", p: ["Permite consultar, a partir de una dirección pública, los saldos por activo, el valor total, el coste medio de adquisición y el rendimiento (P&L) de la posición en OPEN.", "El historial de operaciones devuelve compras, ventas e intercambios con su tipo, importes, precio de ejecución, comisión y marca temporal."] },
      { h: "Webhooks y eventos", p: ["Puedes suscribirte a eventos on-chain —compra, venta, intercambio y recompra/quema— para reaccionar a la actividad en tu propia aplicación.", "Cada evento incluye la dirección implicada (enmascarada cuando procede), los importes y el hash de la transacción, de modo que puedas enlazar al explorador de bloques para su verificación."] },
      { h: "Límites de uso", p: ["La API pública aplica límites por IP y por clave. Si necesitas un caudal superior para una integración en producción, puedes solicitar una clave con límites ampliados.", "Las respuestas incluyen cabeceras con el cupo restante para que tu cliente pueda regular el ritmo de las peticiones."] },
      { h: "Gestión de errores", p: ["La API utiliza códigos HTTP estándar y un cuerpo de error con un identificador legible y un mensaje descriptivo. Las operaciones on-chain pueden revertir; en ese caso, la simulación previa indica el motivo (saldo insuficiente, slippage excedido, allowance insuficiente) antes de gastar comisiones de red."] },
      { h: "Buenas prácticas", p: ["Simula siempre las operaciones antes de enviarlas, muestra al usuario el importe mínimo recibido y las comisiones, y valida las direcciones de los contratos. Nunca solicites ni almacenes claves privadas: toda autorización debe pasar por la firma de la wallet del usuario."] },
    ],
  },
  audit: {
    eyebrow: "Auditoría",
    title: "Seguridad y auditorías",
    meta: "Contratos verificados on-chain",
    subtitle: "Los contratos del protocolo han sido revisados por auditores independientes. El código es abierto y verificable.",
    sections: [
      { h: "Alcance", p: ["La auditoría cubre el token ERC-20, el módulo de recompra/quema y el módulo de gobernanza, incluyendo control de acceso, aritmética de saldos y los flujos de quema."] },
      { h: "Resultados", p: ["Sin hallazgos críticos ni de severidad alta pendientes. Las observaciones de severidad media y baja fueron resueltas y reverificadas. El informe completo está disponible públicamente."] },
      { h: "No custodia", p: ["openAI no custodia los fondos de los usuarios. Los OPEN se envían directamente a la wallet del inversor; solo el usuario controla sus claves privadas."] },
      { h: "Programa de recompensas", p: ["Existe un programa de bug bounty para incentivar la divulgación responsable de vulnerabilidades por parte de la comunidad de seguridad."] },
    ],
  },
  support: {
    eyebrow: "Soporte",
    title: "Centro de soporte",
    meta: "Respuesta media < 24 h",
    subtitle: "¿Necesitas ayuda con una compra, un intercambio o tu wallet? Aquí tienes las vías de contacto y las dudas más frecuentes.",
    sections: [
      { h: "Contacto", p: ["Escríbenos a soporte@openai.demo o a través del chat de la aplicación. El equipo responde en menos de 24 horas en días laborables."] },
      { h: "Problemas con un pago", p: ["Las compras con tarjeta se procesan en Transak o MoonPay. Si un pago queda pendiente, consulta primero el panel del proveedor; desde ahí podrás ver el estado y solicitar asistencia."] },
      { h: "Recuperar el acceso", p: ["openAI no custodia tus claves: si pierdes el acceso a tu wallet, deberás recuperarla con tu frase de recuperación. Nunca compartas tu frase semilla con nadie, tampoco con el soporte."] },
      { h: "Estado del servicio", p: ["Publicamos incidencias y mantenimiento programado en la página de estado. La liquidez on-chain permite operar incluso durante el mantenimiento de la interfaz."] },
    ],
  },
  terms: {
    eyebrow: "Legal",
    title: "Términos y condiciones",
    meta: "Última actualización: 2026",
    subtitle: "Condiciones de uso de la plataforma openAI. Al utilizarla, aceptas los términos descritos a continuación.",
    sections: [
      { h: "1. Naturaleza del servicio", p: ["openAI es una interfaz que facilita la compra, el intercambio y la custodia self-custody del token OPEN. No actuamos como entidad de custodia ni como asesor de inversión."] },
      { h: "2. Elegibilidad", p: ["Debes ser mayor de edad en tu jurisdicción y no residir en territorios donde el uso de criptoactivos esté restringido. Eres responsable de cumplir la normativa aplicable en tu país."] },
      { h: "3. Riesgos", p: ["El valor de OPEN puede fluctuar y podrías perder parte o la totalidad de tu inversión. Operas bajo tu propia responsabilidad y criterio."] },
      { h: "4. Limitación de responsabilidad", p: ["En la máxima medida permitida por la ley, openAI no se hace responsable de pérdidas derivadas del uso de la plataforma, de fallos de terceros (proveedores de pago, wallets) o de la volatilidad del mercado."] },
      { h: "5. Aviso", p: ["Esta web es un concepto de diseño ficticio, sin valor real y sin afiliación con OpenAI. No constituye una oferta de inversión."] },
    ],
  },
  privacy: {
    eyebrow: "Legal",
    title: "Política de privacidad",
    meta: "Última actualización: 2026",
    subtitle: "Cómo tratamos tus datos cuando usas openAI. Recopilamos lo mínimo imprescindible para operar.",
    sections: [
      { h: "1. Datos que tratamos", p: ["Dirección de wallet pública, importes de las operaciones y datos técnicos básicos (dispositivo, idioma). Los datos de tarjeta se procesan íntegramente en Transak o MoonPay; openAI no los almacena."] },
      { h: "2. Finalidad", p: ["Ejecutar tus operaciones, mostrar tu cartera, prevenir el fraude y mejorar el servicio. No vendemos tus datos a terceros."] },
      { h: "3. Conservación", p: ["Conservamos los datos el tiempo necesario para prestar el servicio y cumplir obligaciones legales. La actividad on-chain es pública e inmutable por naturaleza."] },
      { h: "4. Tus derechos", p: ["Puedes solicitar acceso, rectificación o supresión de tus datos personales escribiendo a privacidad@openai.demo."] },
    ],
  },
  risks: {
    eyebrow: "Legal",
    title: "Advertencia de riesgos",
    meta: "Lee esto antes de invertir",
    subtitle: "Invertir en criptoactivos conlleva riesgos significativos. Asegúrate de entenderlos antes de operar.",
    sections: [
      { h: "Volatilidad", p: ["El precio de OPEN puede subir o bajar con rapidez. El rendimiento pasado no garantiza resultados futuros."] },
      { h: "Riesgo de pérdida total", p: ["Podrías perder la totalidad del capital invertido. Invierte únicamente lo que puedas permitirte perder."] },
      { h: "Riesgo tecnológico", p: ["Los contratos inteligentes, aunque auditados, pueden contener vulnerabilidades. La pérdida de tus claves privadas implica la pérdida irreversible de tus fondos."] },
      { h: "Sin asesoramiento", p: ["Esta plataforma no ofrece asesoramiento financiero. Consulta a un profesional independiente si lo necesitas. Recuerda: openAI es un concepto de diseño ficticio, sin valor real."] },
    ],
  },
};

export const docSlugs = Object.keys(docMap);
